- release-notes/opensearch.anomaly-detection-dashboards.release-notes-1.0.0.0-beta1.md
Adds release notes for 1.0.0.0-beta1 release.
> Add release notes for 1.0.0.0-beta1 release

- opensearch_dashboards.json
- package.json
Bumps plugin version to `1.0.0.0-rc1`.
> Bump plugin version to 1.0.0.0-rc1

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0-rc1.md
Adds release notes for version `1.0.0.0-rc1`.
> Add release notes for 1.0.0.0-rc1

- .github/workflows/e2e-tests-workflow.yml
- DEVELOPER_GUIDE.md
- package.json
> [BACKPORT] [1.0] Rename default zip to anomaly-detection-dashboards

- .github/workflows/e2e-tests-workflow.yml
- DEVELOPER_GUIDE.md
- package.json
> [BACKPORT] [1.x] Rename default zip to anomaly-detection-dashboards

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0.md
Add release notes for version 1.0.0.0.
> Add release notes for version 1.0.0.0

- opensearch_dashboards.json
- package.json
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0.md
- yarn.lock
Backporting #45, #47, #46 to `1.x` branch.
> [BACKPORT] [1.x] 1.0.0.0 release changes

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0.md
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
Add rc1 release notes to GA release
> add rc1 release notes to GA release

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0.md
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
Backport #50 to 1.0 branch.
> [Backport] [1.0] add rc1 release notes to GA release

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0.md
Signed-off-by: Yaliang Wu <ylwu@dev-dsk-ylwu-2c-e500d1cf.us-west-2.amazon.com>
Backport #50 to 1.x branch 
> [Backport] [1.x] add rc1 release notes to GA release

- README.md
Signed-off-by: Miki <mehranb@amazon.com>
This change swaps the README image for OpenSearch with a themed one.
> Add themed logo

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.1.0.0.md
Adds release notes for version 1.1.0.0.
Note that if any smaller last-minute changes are made, we don't need to add them to the release notes, as only larger customer-impacting changes should be included in the notes.
> Add release notes for version 1.1.0.0

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.1.0.0.md
Backporting #86 to `1.1` branch.
> [BACKPORT] [1.1] Add release notes for version 1.1.0.0 (#86)

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.1.0.0.md
Backporting #86 to `1.x` branch.
> [BACKPORT] [1.x] Add release notes for version 1.1.0.0 (#86)

- .github/workflows/dco.yml
Signed-of-by: Amit Galitzky amgalitz@amazon.com
Adding working flow to check whether commits are signed as per DCO.
#98
> Add DCO Check Workflow

- server/routes/alerting.ts
Signed-off-by: Yaliang Wu <ylwu@amazon.com>
Search monitors using custom result index.
> search monitors using custom result index

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/Dashboard/Components/AnomaliesDistribution.tsx
- public/pages/Dashboard/Components/AnomaliesLiveChart.tsx
- public/pages/Dashboard/utils/utils.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/DetectorResults/containers/AnomalyResultsLiveChart.tsx
- public/pages/utils/anomalyResultUtils.ts
- public/redux/reducers/__tests__/anomalyResults.test.ts
- public/redux/reducers/anomalyResults.ts
- public/redux/reducers/liveAnomalyResults.ts
- server/cluster/ad/adPlugin.ts
- server/routes/ad.ts
- server/routes/alerting.ts
> Backport main branch commits to 1.2

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/Dashboard/Components/AnomaliesDistribution.tsx
- public/pages/Dashboard/Components/AnomaliesLiveChart.tsx
- public/pages/Dashboard/utils/utils.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/DetectorResults/containers/AnomalyResultsLiveChart.tsx
- public/pages/utils/anomalyResultUtils.ts
- public/redux/reducers/__tests__/anomalyResults.test.ts
- public/redux/reducers/anomalyResults.ts
- public/redux/reducers/liveAnomalyResults.ts
- server/cluster/ad/adPlugin.ts
- server/routes/ad.ts
- server/routes/alerting.ts
> Backport main branch commits to 1.x

- public/pages/DetectorResults/containers/AnomalyHistory.tsx
> [BACKPORT] [1.x] Backport #131 to 1.x

- public/pages/DetectorResults/containers/AnomalyHistory.tsx
> [BACKPORT] [1.2] Backport #131 to 1.2

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
Backporting release notes commit to 1.2
> [BACKPORT] [1.x] Backport #129 to 1.2

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
Backporting release notes commit to 1.x
> [BACKPORT] [1.x] Backport #129 to 1.x

- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
> [BACKPORT] [1.x] Backport #136 to 1.x

- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
> [BACKPORT] [1.2] Backport #136 to 1.2

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
Updated release notes for 1.2.0 AD-dashboards-plugin
> updated release notes for frontend 1.2.0.0

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
> [Backporting to 1.x] updated release notes for frontend 1.2.0.0 (#139)

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
> [Backporting to 1.2] updated release notes for frontend 1.2.0.0 (#139)

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
Changed release notes to use asteriks instead of dashes
> changed release notes to asterisks

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
> [Backporting to 1.x] changed release notes to asterisks (#142)

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
> [Backporting to 1.2] changed release notes to asterisks (#142)

- public/pages/DefineDetector/components/DataFilterList/utils/__tests__/helper.test.ts
> [BACKPORT] [1.x] Backport #146 to 1.x

- public/pages/DefineDetector/components/DataFilterList/utils/__tests__/helper.test.ts
> [BACKPORT] [1.2] Backport #146 to 1.2

- .github/workflows/e2e-tests-workflow.yml
- opensearch_dashboards.json
- package.json
> Bump plugin to 1.3.0.0

- .github/workflows/backport.yml
- DEVELOPER_GUIDE.md
(cherry picked from commit fdda8239a175616999496097a3a8c62865ade562)
Manual backport of #172 since bot is breaking
> [Backport 1.x] add auto backport workflow (#172)

- .github/workflows/backport.yml
> [Backport 1.x] Updating backport workflow to include custom branch name (#173)

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.3.0.0.md
> Add release notes for 1.3.0.0

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
> [1.x] Bump to version 1.4.0.0

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
> Bump to 1.3.1.0

- .github/workflows/remote-integ-tests-workflow.yml
Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.
> Change 2.0-alpha1 to 2.0-rc1.

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.0.0.0-rc1.md
Adding release notes for AD-Dashboards 2.0-rc1
> Adding 2.0-rc1 release notes

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Incremented version to 1.3.2.
Part of https://github.com/opensearch-project/opensearch-build/issues/1882
> Incremented version to 1.3.2.

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.0.0.0.md
> 2.0-GA release notes

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
Currently only running test workflows on `main`. Changing to run on all branches, since release branches are maintained in non-`main` branches and should be checked before merging.
> Run UT/IT on all branches

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101
> Version Increment to 1.3.3 OpenSearch Dashboard release 

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.3.3.0.md
> Add 1.3.3 release notes

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Incremented version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
> Incremented version to 2.0.1

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Increment version to 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
> Incremented version to 1.3.4.

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
> bump to 2.2

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.2.0.0.md
> Add 2.2 release notes

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- server/routes/ad.ts
> Fix a bug in parse response to get expected value

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348
> [Release 1.3.5] Version increment

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Version increment 2.2.1
Part of: https://github.com/opensearch-project/opensearch-build/issues/2481
> Version increment 2.2.1

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
> Bump to 2.3

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Increment version to 1.3.6
Part of https://github.com/opensearch-project/opensearch-build/issues/2650
> Version bump to 1.3.6

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.3.1 to prepare for next patch.
> Bump version to 2.3.1

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.4.0.0.md
> Add 2.4 release notes

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Version bump to 1.3.7
> Version bump to 1.3.7

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- yarn.lock
> [2.3] Fix CVEs & CI

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- yarn.lock
Fix CVEs & CI for `2.1` branch.
> [2.1] Fix CVEs & CI

- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- yarn.lock
Fix CVEs & CI for `1.0` branch.
> [1.0] Fix CVEs & CI

- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- yarn.lock
Fix CVEs & CI for `1.1` branch.
> [1.1] Fix CVEs & CI

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- package.json
- yarn.lock
Fix CVEs & CI for `1.x` branch.
> [1.x] Fix CVEs & CI

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- yarn.lock
Fix CVEs and CI for 2.4 branch
> [2.4] Fix CVEs & CI

- package.json
- yarn.lock
> [2.x] Fix CVEs

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- public/pages/DefineDetector/components/NameAndDescription/NameAndDescription.tsx
- public/pages/DefineDetector/components/Settings/Settings.tsx
- public/pages/DefineDetector/components/Settings/__tests__/__snapshots__/Settings.test.tsx.snap
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
Add windows env to test workflows
> [1.3] Add windows env to test workflow

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.4.1.0.md
> Add 2.4.1 release notes

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.5.0.0.md
> Add 2.5 release notes

- public/pages/DetectorResults/containers/AnomalyResults.tsx
Backport 4ea29db8fde2f1d17b9398ad4d143dd76381d471 from #398
> [Backport 2.5] Update cold start message (#398)

- package.json
- yarn.lock
Bump @sideway/formula to 3.0.1
> Bump @sideway/formula to 3.0.1

- public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorResults/containers/AnomalyResults.tsx
cherry pick this commit from main branch - 2910683012103ac87fc7c037015784b6fe193b45
N/A
> run prettier command against all files

- package.json
- yarn.lock
Update formula and json5 versions 
> [Backport 1.3] Bump @sideway/formula to 3.0.1 (#418)

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.7.0.0.md
Add 2.7 release notes
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/454
> Add 2.7 release notes

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
This PR fixes:
- detection interval and window delay interval initial value not getting filled issue
- flyout footer button won't stay at fixed corner
- flyout is not scrollable
- Feature enhanced accordion is not opened by default
- submit formik with all fields
- minimal accordion default opening
> Fix flyout footer style issue

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/styles.scss
- submit formik with all fields (ex, data filter list)
- form validation
- make feature name and field title dynamically change with the input field
- make newly added feature minimal accordion open by default
~~- make feature name and field title dynamically change with the input field~~
~~- make newly added feature minimal accordion open by default~~
> submit formik with all fields, fix feature list bugs

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/pages/ConfigureModel/components/FeatureAccordion/FeatureAccordion.tsx
> Fix delete button style

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.3.10.0.md
> add 1.3.10 release notes

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
> Fixed order of arguments for creating augmented viz object

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.8.0.0.md
> Add 2.8 release notes

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.8.0.0.md
> add 2.8.0 release notes

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.8.0.0.md
> 2.8 release notes

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
Update accordion title from Advanced Configuration to Advanced configuration
> Update Advanced configuration accordion title

- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- test/jest.config.js
> copy files to resolve conflicts

- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- test/jest.config.js
Keep `jest.config.js` file and `anomalyResultUtils.test.ts` file the same as main branch
> Feature anywhere

- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- test/jest.config.js
previously reverted these two files to make the merge from featureAnywhere branch into main happen. Now adding the change back
> pick changes from featureAnywhere branch into main

- public/expressions/__tests__/overlay_anomalies.test.ts
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
- public/pages/utils/__tests__/anomalyResultUtils.test.ts
Fixing two unit tests that were missed in previous featureAnywhere fixes plus ran prettier. 
> Fixing unit tests plus ran prettier

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.9.0.0.md
> Add 2.9.0 release notes

- opensearch_dashboards.json
- package.json
- yarn.lock
bump to 1.3.12 and also fix some dependency conflicts. 
> increment to 1.3.12 and fix dependency conflicts

- public/pages/DetectorConfig/DetectorConfig.scss
- public/pages/DetectorConfig/containers/DetectorJobs.tsx
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
Removes some unnecessary CSS styling overrides to have consistent text formatting in a few places, and to improve viewing experience in dark mode:
- Detector health badge text
- Detector settings in the detector configuration table
Updates snapshots to prevent failing unit tests.
#572 
> Remove some styling overrides

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.10.0.0.md
2.10 release notes
2.10 release work
> Add 2.10 release notes

- opensearch_dashboards.json
- package.json
> Increment version to 2.11

- opensearch_dashboards.json
- package.json
Increment version to 1.3.14.0
Part of https://github.com/opensearch-project/opensearch-build/issues/4069
> Increment version to 1.3.14.0

- package.json
- yarn.lock
To address Plotly CVE - https://nvd.nist.gov/vuln/detail/CVE-2023-46308
https://nvd.nist.gov/vuln/detail/CVE-2023-46308
> Update Plotly version to the latest to resolve CVE

- test/jest.config.js
- yarn.lock
> Bump `@adobe/css-tools` to 4.3.3

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.13.0.0.md
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/682
> Adding 2.13 release notes

- .github/workflows/build-and-test-workflow.yml
- .github/workflows/remote-integ-tests-workflow.yml
- package.json
- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- public/pages/utils/anomalyResultUtils.ts
- release-notes/opendistro-for-elasticsearch.anomaly-detection-kibana-plugin.release-notes-1.7.0.0.md
backport [PR 741](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/741)
> backport build query parameters using data_end_time

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.14.0.0.md
Adds release notes for 2.14.0 release
Part of #707 
> Add release notes for 2.14.0

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AssociateExisting/containers/AssociateExisting.tsx
- public/expressions/helpers.ts
- public/expressions/overlay_anomalies.ts
support MDS in feature anywhere, including the following changes:
- create/list detector with dataSourceId
- when creating the saved object, include the dataSourceId as an argument together with detectorId. 
- reading the dataSourceId in `overlay_anomalies` file from the saved object together with detectorId
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/assets/41348518/d9212778-c994-45f1-8b14-cae654ce5a0e
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
> support MDS in feature anywhere

- opensearch_dashboards.json
- package.json
Update 2.x to 2.15.0
https://github.com/opensearch-project/opensearch-build/issues/4681
> Update 2.x to 2.15.0

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.15.0.0.md
> adding 2.15 release notes

- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
updating snapshot and adding null check before getting index patterns
> Updating snapshot and adding null check on embeddable

- opensearch_dashboards.json
- public/pages/ConfigureModel/containers/ConfigureModel.tsx
- public/pages/Dashboard/Container/DashboardOverview.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/DetectorDetail/containers/DetectorDetail.tsx
- public/pages/DetectorJobs/containers/DetectorJobs.tsx
- public/pages/DetectorsList/containers/List/List.tsx
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
- public/pages/ReviewAndCreate/containers/ReviewAndCreate.tsx
- public/pages/utils/helpers.ts
- tsconfig.json
- yarn.lock
This pr adds a version filter function that supports MDS version decoupling
> MDS Version Decoupling

- public/anomaly_detection_app.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
- public/pages/Overview/containers/__tests__/AnomalyDetectionOverview.test.tsx
- public/pages/Overview/containers/__tests__/__snapshots__/AnomalyDetectionOverview.test.tsx.snap
- public/pages/main/Main.tsx
- public/plugin.ts
- public/utils/constants.ts
This PR adds new navigation changes for AD
https://github.com/user-attachments/assets/7fb3ffb6-00f1-48cc-8894-5b7cda11e7c2
Related Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029
> AD side navigation redesign

- public/plugin.ts
side nav redesign change update - removing AD form security analytics group
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029
> side nav redesign change update

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.16.0.0.md
> Add 2.16 release note

- public/plugin.ts
> feat: show anomoly detection in left navigation

- package.json
- yarn.lock
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
(cherry picked from commit 25726fb0534b15dc70fe87641a4c4dd92c456327)
> [Backport 1.3] address CVE-2024-4068 (#823)

- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
> Fix description on overview page

- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
> Fix custom result index session not rendering issue

- server/routes/opensearch.ts
backporting  https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/886 to 2.x 
> [Backport 2.x] Fallback to cluster health 

- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
- public/redux/reducers/ad.ts
> [Backport 2.17] Fix issues in running historical analysis and custom result index section

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- public/components/DiscoverAction/SuggestAnomalyDetector.test.tsx
- public/components/DiscoverAction/SuggestAnomalyDetector.tsx
- public/pages/ConfigureModel/components/FeatureAccordion/FeatureAccordion.tsx
- public/plugin.ts
- public/redux/reducers/__tests__/ad.test.ts
- public/redux/reducers/__tests__/opensearch.test.ts
- public/redux/reducers/ad.ts
- public/redux/reducers/opensearch.ts
- public/services.ts
- public/utils/constants.ts
- public/utils/contextMenu/getActions.tsx
- server/utils/constants.ts
We sync the commits as below:
- cherry-pick https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/commit/1430126cf561089e81659a38da53f84bc9965f5b
- cherry-pick https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/commit/a27d1df68edf765f5d7fa638e5dc39fca872028d
- cherry-pick https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/commit/d199322d654ff38bb5d11182ececbe1f8d47d75e
- revert https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/commit/71c38423a4f310d34fd75bfbbdb4bd433399e495
For more information on following Developer Certificate of Origin and …
> Sync code from 2.x to mds-2.17

- package.json
- yarn.lock
Remove unnecessary dep. Cleaned up lockfile automatically after running `yarn remove start-server-and-test`.
> Remove unnecessary dep

- public/action/ad_dashboard_action.tsx
Update vis augmenter eligibility fn to async. Related to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8915
> Update vis augmenter eligibility fn to async

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.3.20.0.md
Adds release notes for 1.3.20 release
> Add release nodes for 1.3.20

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/verify-binary-installation.yml
- opensearch_dashboards.json
- package.json
Follow https://github.com/opensearch-project/dashboards-query-workbench/pull/444
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/568
> Bump to version 3.0.0.0-alpha1

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-3.0.0.0-alpha1.md
> Adding release notes for 3.0-alpha1

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Update remote test workflow branch
> Update remote test workflow branch and Increment version to 2.19.2

- package.json
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.19.2.0.md
- yarn.lock
bumping axios and babel versions
> bumping babel and axios versions

- public/pages/Dashboard/Container/DashboardOverview.tsx
- public/pages/DetectorsList/containers/List/List.tsx
- public/pages/DetectorsList/utils/helpers.ts
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
Fix a mds bug that could cause detectors won't show in localhost scenario by removing the check on `MDSOverviewState.selectedDataSourceId !== ""` before doing dispatch call
> fix a mds bug

- .github/workflows/changelog_verifier.yml
- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/verify-binary-installation.yml
- CHANGELOG.md
- public/pages/DefineForecaster/components/AggregationSelector/AggregationSelector.tsx
- public/pages/DefineForecaster/components/AggregationSelector/__tests__/__snapshots__/AggregationSelector.test.tsx.snap
- public/pages/DefineForecaster/components/ForecastCategory/ForecastCategory.tsx
- public/pages/ForecastDetail/components/ForecastChart/ForecastChart.tsx
- public/pages/ForecastDetail/containers/ForecasterDetail.tsx
- public/pages/ForecastDetail/utils/dateUtils.ts
- public/redux/middleware/clientMiddleware.ts
- server/routes/ad.ts
- server/routes/utils/forecastHelpers.ts
This PR
- Corrected helper text for forecasting indicators (previously copied from anomaly detection).
- Fixed plotting bug: explicitly check for null to avoid skipping data points with a value of 0.
- Added data-test-subj attributes to improve testability.
- Implemented handling for absolute date inputs (e.g., "2020-01-01T21:52:56.000Z") from date picker.
- Removed unnecessary console.log statements.
Testing done:
- added IT: https://tinyurl.com/2yzmaby7
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTIN …
> Improve indicator helper, fix zero-value plotting etc

- public/pages/DetectorResults/__tests__/AnomalyResultsTable.test.tsx
- public/pages/DetectorResults/containers/AnomalyResultsTable.tsx
> fix ribon encoding issue in contextual launch

- CHANGELOG.md
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-3.2.0.0.md
update changelog to be up to date post 3.1
> Updating changelog and 3.2 release notes

- package.json
- test/jest.config.js
- yarn.lock
forcing resolution of pbkdf and form-data to latest versions
> Bumping pbkdf and form-data dependencies
