opensearch-project/anomaly-detection-dashboards-plugin

- .github/workflows/unit-tests-workflow.yml
- README.md
- opensearch_dashboards.json
- package.json
Fixes the unit test workflow so it can successfully run against opened PRs in addition to merges to the main branch.
Updates the plugin version and OpenSearch Dashboards compatibility to 1.0.0.0 and 1.0.0, respectively.
Once OpenSearch Dashboards has versioned branches, the `main` can revert back to a version (e.g., `7.10.2` branch).
Passing workflow: see [here](https://github.com/ohltyler/anomaly-detection-dashboards-plugin-1/actions/runs/768905398)
Partially resolves the overall workflow updates (#2)
Resolves #4  …
> Reset plugin version to 1.0.0.0, fix UT workflow

- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.0.0.0-beta1.md
Bumps the plugin version to `1.0.0.0-beta1` and OpenSearch Dashboards compatibility to `1.0.0-beta1`.
- All unit + integ tests pass locally
- Installed zip in `1.0.0-beta1` Dashboards binary & sanity tested
> Bump plugin version to 1.0.0.0-beta1

- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/SampleData/components/SampleDetailsFlyout/SampleDetailsFlyout.tsx
- public/pages/SampleData/containers/SampleData/SampleData.tsx
- public/pages/SampleData/utils/constants.tsx
- public/pages/SampleData/utils/helpers.tsx
- public/pages/utils/constants.ts
- server/routes/sampleData.ts
Current sample detectors and indices include the legacy `opendistro-` prefix. This PR removes that prefix.
Example: 
eCommerce detector change: `opendistro-sample-ecommerce-detector` => `sample-ecommerce-detector`
eCommerce index change: `opendistro-sample-ecommerce` => `sample-ecommerce`
In addition:
- Handled backwards compatibility by ensuring legacy detectors created are still recognized as created on the sample detectors page
- Changed the sample details flyout to pull the detector & index names from an existing detector if possible. That way, new and legacy detectors will both be properly reflected
- Added legacy checks to helper fns and query parameters to search for both new and legacy created detectors and indices
- Confirmed newly named detectors/indices function the same as …
> Update sample data naming conventions

- .github/workflows/e2e-tests-workflow.yml
- package.json
Fixes the CI workflow to run against the OpenSearch staging docker images with the `latest` tag. Also updates the workflow to run against PRs and not just on merges to main.
NOTE: this is still checking out the `1.0.0-beta1` tag for the core repos. This workflow (as well as the other repos) will be changed once there is a dedicated branch or consistent way for plugins to build and test against the latest versions of the core repos.
Resolves #2
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …
> Fix CI workflows; change to run against PR

- server/utils/constants.ts
Updates the API calls to use the new `_plugins/` endpoint prefix in favor of the legacy `_opendistro/*` endpoint prefix.
Current list of anomaly detection API calls being updated: [here](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/server/cluster/ad/adPlugin.ts)
Current list of alerting API calls being updated: [here](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/server/cluster/ad/alertingPlugin.ts)
Have tested all anomaly detection calls made. …
> Update API call endpoints from _opendistro to _plugins

- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
Updates the test workflows to run against the `1.x` branch. Removes unnecessary env variable in the CI workflow.
> Change workflows to run against 1.x branch

- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
Now that OpenSearch Dashboards has been frozen for `1.0`, build and test against this version.
Also increases the timeout in the CI workflow (without security) which was causing occasional failures in the github runners.
> Update workflows to run against 1.0 branch

- .github/workflows/e2e-tests-workflow.yml
Changes the CI to run against the `1.0.0-rc1` staging docker images.
> Run CI against 1.0.0-rc1 docker images

- .github/workflows/link-check-workflow.yml
- README.md
- public/pages/AnomalyCharts/components/AlertsFlyout/__tests__/__snapshots__/AlertsFlyout.test.tsx.snap
- public/pages/CreateHistoricalDetector/components/Configuration/__tests__/__snapshots__/Configuration.test.tsx.snap
- public/pages/CreateHistoricalDetector/components/Configuration/components/__tests__/__snapshots__/Features.test.tsx.snap
- public/pages/CreateHistoricalDetector/containers/__tests__/__snapshots__/CreateHistoricalDetector.test.tsx.snap
- public/pages/Dashboard/Components/EmptyDashboard/__tests__/__snapshots__/EmptyDashboard.test.tsx.snap
- public/pages/EditFeatures/components/CategoryField/__tests__/__snapshots__/CategoryField.test.tsx.snap
- public/pages/SampleData/components/SampleDataCallout/__tests__/__snapshots__/SampleDataCallout.test.tsx.snap
- public/pages/createDetector/containers/__tests__/__snapshots__/CreateDetector.test.tsx.snap
- public/utils/constants.ts
Adds a broken link checker workflow. Runs on pushes & pull requests to `main`. Based off of the `opensearch-plugins` [PR](https://github.com/opensearch-project/opensearch-plugins/pull/54).
> Add broken link check workflow

- .github/workflows/e2e-tests-workflow.yml
- DEVELOPER_GUIDE.md
- package.json
Renames default zip from the camelCased `anomalyDetectionDashboards` to the kebab-cased `anomaly-detection-dashboards`.
Only affects zip - not plugin name (as seen in the url) or plugin ID.
> Rename default zip to anomaly-detection-dashboards

- opensearch_dashboards.json
- package.json
Bumps the plugin version to `1.0.0.0` by removing the `rc1` version qualifier.
> Bump to version 1.0.0.0

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/HistoricalDetectorResults/components/EmptyHistoricalDetectorResults/EmptyHistoricalDetectorResults.tsx
- public/pages/HistoricalDetectorResults/components/EmptyHistoricalDetectorResults/index.ts
- public/pages/HistoricalDetectorResults/components/HistoricalDetectorCallout/HistoricalDetectorCallout.tsx
- public/pages/HistoricalDetectorResults/components/HistoricalDetectorCallout/index.ts
- public/pages/HistoricalDetectorResults/components/HistoricalRangeModal/HistoricalRangeModal.tsx
- public/pages/HistoricalDetectorResults/components/HistoricalRangeModal/index.ts
- public/pages/HistoricalDetectorResults/containers/HistoricalDetectorResults.tsx
- public/pages/HistoricalDetectorResults/utils/constants.tsx
- public/pages/utils/anomalyResultUtils.ts
- public/pages/utils/constants.ts
- public/utils/constants.ts
- server/utils/constants.ts
**This PR is 5 of 9 related to the new single flow changes. We will merge all changes into the single-flow-development branch first, and finally merge into main.**
**Please ignore test-related code for now, this is currently being refactored and updated, will be addressed in a later PR**
This PR adds the historical tab on the detector details page. Specifically, the changes include:
- Adding support to start and stop a historical task, and view the historical anomaly results and feature results
- An empty state for when no historical tasks have been created prior
- Modals to create and modify the historical detector date range
- Showing partial historical results as the task is running - will automatically refresh every 10s (same as …
> [SINGLE FLOW] Add historical results tab

- .cypress/integration/ad/dashboard/ad_dashboard.spec.ts
- .cypress/integration/ad/detectorList/detector_list.spec.ts
- .cypress/integration/ad/workflow/create_detector.spec.ts
- .cypress/plugins/index.js
- .cypress/support/commands.ts
- .cypress/support/index.d.ts
- .cypress/support/index.js
- .cypress/utils/constants.ts
- .cypress/utils/helpers.ts
**This PR is 9 of 9 related to the new single flow changes. We will merge all changes into the single-flow-development branch first, and finally merge into main.**
Updates Cypress integration tests. 2 types of changes are done:
1. Updating them to be compatible with OpenSearch
2. Minor change to a Dashboard page test case - changing to test running detectors to fix flaky test related to stopped detector case
> [SINGLE FLOW] Update integration tests 

- public/pages/ConfigureModel/components/CategoryField/CategoryField.tsx
- public/pages/ConfigureModel/components/CategoryField/__tests__/CategoryField.test.tsx
- public/pages/ConfigureModel/containers/ConfigureModel.tsx
- public/pages/ConfigureModel/utils/constants.tsx
- public/pages/ConfigureModel/utils/helpers.ts
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorConfig/containers/Features.tsx
- public/pages/DetectorResults/utils/utils.ts
- public/pages/ReviewAndCreate/components/ModelConfigurationFields/ModelConfigurationFields.tsx
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/pages/ReviewAndCreate/utils/__tests__/helpers.test.tsx
- public/redux/reducers/__tests__/utils.ts
- public/utils/constants.ts
Previously, we hardcoded HCAD (including real-time and historical) shingle size to be one due to time constraints when releasing HCAD. This PR enabled shingling in HCAD on the frontend (backend PR: https://github.com/opensearch-project/anomaly-detection/pull/187). Specifically, after this PR
* both single-stream and HCAD detectors have a default shingle size of 8.
* no special handling of HCAD detectors' shingle size.
Testing done:
1. unit tests and cypress tests pass.
2. Manual testing to verify HCAD real-time and historical tasks use shingle eight by default and can use customized size.
3. Manual testing to verify preview uses shingle eight by default and can use the customized size.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Enable shingle in HCAD

- public/pages/DetectorDetail/containers/DetectorDetail.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
This PR fixes 2 bugs found when testing out the single flow feature:
1. Historical analysis task not being taken into consideration when editing the detector settings or model config. The fix: add checks for if the historical task is running or not before editing, and add verbose messaging around that. Added a custom hook which will automatically close the modal if the detector task states have been changed after opening the modal (e.g., the historical analysis was `RUNNING` when initially opened, but was changed to `FINISHED` soon after).
2. 'The detector was stopped' messaging showing up when selecting a heatmap cell for a historical high-cardinality detector, during a timeframe where the corresponding real-time task was not running. The …
> Bug fixes for single flow feature

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- public/pages/DetectorResults/containers/AnomalyResultsTable.tsx
This PR adds zooming capabilities to the anomaly chart when selecting a heatmap cell for high-cardinality detectors.
Changes include:
- `AnomaliesDetailChart`: Allowing zooming for high-cardinality detectors
- `FeatureBreakDown`: Setting the date range based on the passed-in date range (which is `zoomRange`) instead of the heatmap cell. This is so we can narrow the range if the user zooms, rather than leaving it at the heatmap cell's static range.
- `AnomalyHistory`: setting the `zoomRange` when a heatmap cell is selected or de-selected, to refresh any stored data in the components. This is needed since `FeatureBreakDown` now relies on the `zoomRange` to get the date range. 
- `AnomalyResultsTable`: Only populate with anomalies when …
> Enable zooming in HC entity charts

- public/pages/ConfigureModel/components/CategoryField/CategoryField.tsx
- public/pages/ConfigureModel/components/CategoryField/__tests__/CategoryField.test.tsx
- public/pages/ConfigureModel/components/CategoryField/__tests__/__snapshots__/CategoryField.test.tsx.snap
- public/pages/ConfigureModel/containers/__tests__/__snapshots__/ConfigureModel.test.tsx.snap
This PR blocks users from editing the selected category fields after initial detector creation. The reason for this change is because the anomaly results and charts can get in weird states if the detector cardinality type is changed, and lead to showing confusing and/or misleading data to the users (e.g., making a single-category high-cardinality detector into a non-high-cardinality detector will show multiple results with the same timestamp for each entity).
Changes include:
- Adding callouts to the model config page describing the changes. In the creation flow, show a warning callout once the user initially enables the category field checkbox. In the edit flow, show an info callout describing why the category field selections (enabled or …
> Add callouts and make category fields readonly after creation

- public/pages/DetectorResults/containers/AnomalyHistory.tsx
Currently, if a user selects a heatmap cell, the (1) anomaly chart, (2) anomaly table, and (3) feature chart are populated below. When the user changes any of the heatmap chart filters (top 10 / top 20 / top 30, sort by # occurrences / sort by severity, etc.), the data in these 3 components are cleared, since new cells will be generated, and the previously-selected one may not be available anymore.
However, changing the date range will not clear the state, even though it is also directly affecting the heatmap chart, and could lead to confusing UI if the results aren't cleared. This PR fixes that by clearing data when the date range is changed.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Clear HC charts when the date range changes

- public/pages/ConfigureModel/components/CategoryField/CategoryField.tsx
- public/pages/ConfigureModel/components/CategoryField/__tests__/__snapshots__/CategoryField.test.tsx.snap
- public/pages/ConfigureModel/containers/__tests__/__snapshots__/ConfigureModel.test.tsx.snap
The wording has been tuned for the new category field callouts. This PR addresses that.
> Tune wording on category field callouts

- .github/workflows/CD.yml
- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Bumps plugin version to `1.1.0.0`, and related dependencies to `1.1.0`.
Testing:
Ran the unit and integration tests locally & successfully. Note that the integration test GitHub workflows will fail for now due to the `1.1.0`-tagged docker images not existing yet. I've attached the locally-ran output in a comment below.
I also did a sanity test that core functionality is working. Set up a 1.1 cluster with the latest AD backend changes based on `main` branch (last commit: [here](https://github.com/opensearch-project/anomaly-detection/commit/bedc5b620384163abe272e913705fa23cfd3b3a3)).
For more information on following Developer …
> Bump plugin version to 1.1.0.0

- .github/workflows/CD.yml
- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- public/pages/ConfigureModel/components/CategoryField/CategoryField.tsx
- public/pages/ConfigureModel/components/CategoryField/__tests__/__snapshots__/CategoryField.test.tsx.snap
- public/pages/ConfigureModel/containers/__tests__/__snapshots__/ConfigureModel.test.tsx.snap
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
Backports the last 3 PRs into `1.x` branch. Now includes all necessary changes for cutting a `1.1` branch.
> [BACKPORT] [1.x] Backport remaining PRs to 1.x

- .github/workflows/e2e-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
Change the workflows in `1.1` branch to now explicitly use the core Dashboards `1.1` branch, now that it has been cut.
> [1.1] Change workflows to use core 1.1 branch

- public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
Fixes the bug of the filters for "Top 20" / "Top 30" not updating correctly when selected for historical high-cardinality charts. The fix is to update the hook to use any existing filter state, rather than defaulting to "Top 10" and overriding any existing state.
Note that if the hook was working as expected, this original bug wouldn't exist, since it would only be triggered when changes to the `props.detectorTaskProgress` happen (when the historical task is running). But, it is actually being triggered when any filter selection is made. It was then found that the entire `AnomalyHeatmapChart` component is getting re-mounted whenever these filter changes are occurring, hence triggering this hook every time a re-mount happens.
Expected …
> Fix bug of HC historical results not showing top 20/30

- public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
Backporting #91 to `1.1` branch.
> [BACKPORT] [1.1] Fix bug of HC historical results not showing top 20/30 (#91)

- public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
Backporting #91 to `1.x` branch.
> [BACKPORT] [1.x] Fix bug of HC historical results not showing top 20/30 (#91)

- public/models/interfaces.ts
- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyOccurrenceChart.tsx
- public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
- public/pages/AnomalyCharts/containers/__tests__/AnomaliesChart.test.tsx
- public/pages/AnomalyCharts/containers/__tests__/AnomalyHeatmapChart.test.tsx
- public/pages/AnomalyCharts/containers/__tests__/FeatureBreakDown.test.tsx
- public/pages/AnomalyCharts/containers/__tests__/__snapshots__/AnomalyHeatmapChart.test.tsx.snap
- public/pages/AnomalyCharts/utils/anomalyChartUtils.tsx
- public/pages/ConfigureModel/containers/SampleAnomalies.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- public/pages/DetectorResults/utils/constants.ts
- public/pages/utils/anomalyResultUtils.ts
- public/redux/reducers/anomalyResults.ts
- server/cluster/ad/adPlugin.ts
- server/routes/ad.ts
- server/utils/constants.ts
This PR adds support for filtering results on a subset of categorical fields. For example, if a user has 2 categorical fields selected, they can now search for the top values of one field, ignoring the other. And, when selecting a value of one of these fields, a sorted list of the top values of the other field is displayed for viewing on the anomaly and feature charts. This is supported for both real-time and historical scenarios.
The primary changes in this PR include:
- Adding support for new multi-category filtering API (see [backend PR](https://github.com/opensearch-project/anomaly-detection/pull/261))
- Adding a combo box filter at the top of the charts to select some subset of categorical fields, rather than a hardcoded string that includes all of the fields.
- Adding a combo box …
> Support multi-category filtering of results

- server/routes/ad.ts
Fixes an edge case where calls to the search task API will fail if the `.opendistro-anomaly-detection-state` system index doesn't exist, which will only happen on a fresh cluster that has never ran any detector job (once any job is ran,the system index is created).
This fixes all places where the search task API is called on server-side, and wraps in a separate try/catch to suppress any `index_not_found_exception`, so that the rest of the logic can be executed normally.
The side effects of this bug (which are now fixed):
1. Detector list will fail to show any detectors, shows error toast saying error getting all detectors
2. Detector details pages will fail, shows error toast saying error getting detector
Closes #109 
By submitting this …
> Fix bug of detector task calls failing if no state index

- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
Fixes a bug in the non-high-cardinality scenario where anomaly and feature charts were showing the explicit range based on the timestamps of anomaly results found in the parent date range, rather than showing the static date range itself. (see #121 for details/screenshots).
This fixes that bug by 2 main changes:
1. Explicitly setting the range of `x` values for the chart via `xDomain` chart prop for both anomaly details and feature charts
2. Splitting up the logic for HC and non-HC results, when the zoom range is changed. For example, in the non-HC scenario, if the zoom range is changed, we want to update the parent date range (as shown in the date range picker). In the HC scenario, we only want to change the range shown on the child …
> Fix chart range bug of non-HC anomaly and feature charts

- public/pages/AnomalyCharts/components/AlertsButton/AlertsButton.tsx
- public/pages/AnomalyCharts/components/AlertsFlyout/AlertsFlyout.tsx
- public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
- public/utils/utils.tsx
Signed-off-by: Yaliang Wu <ylwu@amazon.com>
When user click set up alerts button on detector realtime result page, we need to pass AD result index to monitor creation page, so the monitor can query correct AD result index.
> support create monitor with custom result index

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/Dashboard/Components/AnomaliesDistribution.tsx
- public/pages/Dashboard/Components/AnomaliesLiveChart.tsx
- public/pages/Dashboard/utils/utils.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/DetectorResults/containers/AnomalyResultsLiveChart.tsx
- public/pages/utils/anomalyResultUtils.ts
- public/redux/reducers/__tests__/anomalyResults.test.ts
- public/redux/reducers/anomalyResults.ts
- public/redux/reducers/liveAnomalyResults.ts
- server/cluster/ad/adPlugin.ts
- server/routes/ad.ts
Signed-off-by: Yaliang Wu <ylwu@amazon.com>
Only query custom result index for detector detail page. Query both default and custom AD result index on dashboard and detector list page.
> search only custom result index on detector detail page

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-1.2.0.0.md
Adds release notes for version 1.2.0.0
#97 
> Add release notes for version 1.2.0.0

- public/pages/DetectorResults/containers/AnomalyHistory.tsx
Fixes a bug where heatmap chart data doesn't auto-refresh properly in the historical scenario. Note that the data would still show fine if the page was refreshed (switched tabs, etc.).
The bug was that the entity-level anomaly summaries weren't being fetched during the auto-refresh codepath, and were always being passed as an empty list. The heatmap chart data is prepared using the summaries, and so because the summaries were always empty, the heatmap chart data was always subsequently empty.
The fix is to add a call to fetch the entity summaries (`fetchHCAnomalySummaries()`) after fetching the raw results (`fetchRawAnomalyResults()`) in `AnomalyHistory`, which is rendered as a child component in `HistoricalDetectorResults`. Note that …
> Fix bug of HC historical results not auto-refreshing

- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
When the feature charts are rendered as a child component in the `AnomalyHistory` container, the annotations aren't formatted properly. This is due to one missed place where the annotations weren't converted into 2D arrays, where they should have been as part of #107. The proper conversion is already done when the feature chart is rendered as a child of `AnomaliesChart` container (see [here](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/public/pages/AnomalyCharts/containers/AnomaliesChart.tsx#L349)). Additionally, the `FeatureChart` wasn't handling the new 2D representation of annotations, so that is fixed as well. Added some clarification comments above that change.
The side effect of this bug is that …
> Fix bug of missing annotations on feature charts

- public/pages/DefineDetector/components/DataFilterList/utils/__tests__/helper.test.ts
Clean up one Amazon header that was missed in #118.
Note that from the [parent issue](https://github.com/opensearch-project/.github/issues/21), and from #67, new OpenSearch files (files not from Open Distro) can be created using the short version of the header now:
```
/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*/
```
> Remove remaining Amazon header

- .github/CODEOWNERS
Signed-off-by: Ryan Bogan <rbogan@amazon.com>
Adds support for codeowners to repo
Progress on:
[Meta issue](https://github.com/opensearch-project/project-meta/issues/31)
> Add codeowners support to repo

- .github/workflows/unit-tests-workflow.yml
Fixes the codecov GitHub action which had a typo.
> Enable codecov in repository UT workflow

- public/pages/AnomalyCharts/containers/AnomalyHeatmapChart.tsx
Plotly tries to determine the axis type based on the input data given. For the y-axis in the heatmap chart, we don't want this functionality, since all given data is values for a given categorical field, so it should always be categorical. This PR forces the axis type to be `category`. See more details on axis `type` functionality [here](https://plotly.com/python/reference/layout/yaxis/#layout-yaxis-type).
This fixes a significant bug, where currently all values read as numerical by plotly will cause overlapping axes and an unreadable heatmap chart:
After the fix, that same data now renders properly:
#166 
For more information …
> Force heatmap y-axis to be category type

- .github/ISSUE_TEMPLATE/bug_template.md
> Remove Beta label from bug issue template

- .whitesource
- whitesource.config
We @bbarani already enable the access of [WhiteSource integration](https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com) with Github.com for this repo. However, the automatic PR of .whitesource is not created. We asked for the support from WhiteSource side and they suggested we could raise one by ourselves. This PR will also set the WhiteSource integration config mode `LOCAL` so it will be using the `whitesource.config` in the root directory. Dashboards team can modify this configuration on their own to customize it. We are providing the one we had for all repos at this time.
Another PR we created for the same issue. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/999
Please be aware …
> Add .whitesource and config files to activate whitesource integration

- .github/workflows/backport.yml
- DEVELOPER_GUIDE.md
Adds backport workflow to allow automatic backport PR creation as we merge to main or label PR. Explanation of script added to documentation.
* We can label previously closed PRs and the action will run.
* As of right now we have to manually delete the branch that the bot creates. This could be changed in the future to be automatic.
resolves #157 
> add auto backport workflow

- public/pages/ReviewAndCreate/components/FilterDisplayList/FilterDisplayList.tsx
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
This PR fixes that a new detector with custom filter created using API cannot show.
Testing done:
1. Created a detector with a custom filter using API and verified the change fixed the issue.
Before:
After:
> Fix custom expression filter cannot show

- yarn.lock
Manual PR related to #177. Bumping `follow-redirect` to 1.14.8. Verified functionality on local cluster.
> Upgrade follow-redirect dependency

- .github/workflows/e2e-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Manual backport of #160 to 1.x. Bot was failing saying conflicts, but when performing manual steps, there was no conflicts. Probably some bug in the bot.
> [Backport 1.x] Bump plugin to 1.3.0.0 (#160)

- public/models/interfaces.ts
- public/pages/DefineDetector/utils/constants.tsx
- public/pages/ReviewAndCreate/components/DetectorDefinitionFields/DetectorDefinitionFields.tsx
- public/pages/ReviewAndCreate/components/FilterDisplayList/FilterDisplayList.tsx
- public/pages/ReviewAndCreate/components/ModelConfigurationFields/ModelConfigurationFields.tsx
- public/pages/ReviewAndCreate/containers/ReviewAndCreate.tsx
- public/redux/reducers/ad.ts
- server/cluster/ad/adPlugin.ts
- server/routes/ad.ts
This PR integrates the new additional type parameter for validation API that includes `model` validation. Since `model` (non-blocker) validation also runs `detector` (blocker) validation, currently I only call the validate API with `model` parameter. In the future we can separate the two if we want to make the non-blocker validation an optional action. With this API integrated the user will be able to see any non-blocking issues.
* If response type is model then object passed to model or detector definition will include that information and the callout will be of color `warning` instead of `danger`
For more information on …
> Non blocker

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR adds a labeling github action which is triggered on PRs opening to `main`. There are 2 added files:
1. `.github/labeler.yml`: configures the labels to add to the PR, if the PR's changed files match any of the glob patterns specified. For example, this adds a `dependencies` label whenever a PR is opened that changes `yarn.lock`.
2. `.github/workflows/labeler.yml`: the actual github action which uses the specified config. Uses permissions from the OpenSearch GitHub app to be able to write to the PR, since that is not possible using the default `GITHUB_TOKEN`. For more details see [here](https://github.com/actions/labeler/pull/51/files), [here](https://github.com/actions/first-interaction/issues/10)
Example PR of this working in my …
> Add auto labeler workflow

- README.md
Signed-off-by: Tyler Ohlsen ohltyler@amazon.com
Updates the integ test workflow badge link to point to the new remote integ tests workflow. The current link is pointing to an old workflow that doesn't exist anymore.
> Update integ tests badge in README

- .github/workflows/remote-integ-tests-workflow.yml
Now that functional-test repo supports matching branching strategies as core Dashboards, the CI workflow can point to that branch to run tests instead of the default `main`.
Note this is just for `1.x` branch. `main` branch can stay on `main`, and will work once AD is bumped to `2.0.0`
> [1.x] Change integ test repo test branch

- opensearch_dashboards.json
- package.json
To be supported within the distribution for OSD 2.0.0-rc1 from the build repo, plugins need to ensure their plugin version is the expected version until https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1398 is addressed. If OSD plugins version does not match the qualifier of the build then the build will fail. 
Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
n/a
> [Build] bump to 2.0.0.0-rc1

- public/pages/DetectorConfig/containers/DetectorConfig.tsx
Removes extra loading spinners on detector config page.
Closes #94
> Remove extra loading spinners

- .github/configurations/docker-compose.yml
- public/pages/DetectorDetail/containers/DetectorDetail.tsx
Remove additional loading spinners that were accidentally added and changing `master` in docker compose setting to `cluster_manager`
> remove additional loading spinners and removing master from docker compose

- .github/labeler.yml
Update labeler to default backports to `2.x` branch.
> Update labeler to default backports to 2.x

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
- yarn.lock
remove rc1 qualifier
resolves #254 
> Remove rc1 qualifier

- public/pages/DetectorDetail/containers/DetectorDetail.tsx
Added two new conditions to two different `useEffect` calls on `DetectorDetail` page. 
First change is to wait for getDetector request to finish loading before checking if the indices themselves exist. Currently we are checking if the indices exist on every change to the detector and while the detector is still loading it continuously loops this API call to check for indices. This then triggers a change in AppState which triggers the change in `detector` variable hence the loop.
The second change is under the same idea where we don't need to call the `useEffect` that calls on `hideStopDetectorModal` if the detector itself is empty.
Further improvements will be made in later PR to optimize `useFetchDetectorInfo` further which is the call …
> Wait for detector to load before checking indices exist

- opensearch_dashboards.json
- package.json
- public/models/interfaces.ts
- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/FeatureBreakDown.tsx
- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- public/pages/utils/anomalyResultUtils.ts
The missing feature callout only shows when fetching feature data points based on the interval and time range, and if there are any empty points Previously, when I configured the window delay to 20 minutes, the missing data call out will show. The reason is that the window delay offset isn't being considered in the time range used in the feature fetching query, or in the displayed chart, such that it shows as empty, when it's actually expected to be empty based on the window delay.This PR fixed the bug by considering window delay in missing feature calculations.
Testing done:
1. done e2e testing and verified the problem is fixed.
2. added unit tests.
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/223
By …
> Fix missing data call out if window delay is large

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
- opensearch_dashboards.json
- package.json
Bump plugin to `2.1.0.0`, and compatibility with core Dashboards `2.1.0`.
> Bump to 2.1.0 compatibility

- public/models/interfaces.ts
- public/pages/AnomalyCharts/components/FeatureChart/FeatureChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/AnomalyCharts/utils/anomalyChartUtils.tsx
- public/pages/AnomalyCharts/utils/constants.ts
- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- public/pages/utils/anomalyResultUtils.ts
- server/models/types.ts
- server/routes/ad.ts
UI changes:
- in anomaly result chart, show feature contribution of this anomaly with RectAnnotation component
- in feature break down chart, show expected value when there's an anomaly and current value when there's no anomaly as an additional <LineSeries> on the chart
- swap feature break down tab with anomaly occurrence tab to make it the default selected tab
https://github.com/opensearch-project/anomaly-detection/issues/299
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …
> Add feature attribution

- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
Fix failed unit tests by adding a isArray check to catch potential non array input
> fix failed unit tests

- server/routes/ad.ts
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
> Fix undefine expect value for feature attribution

- yarn.lock
Bump `moment` to 2.29.4.
Manual fix of #295 
> Upgrade moment to 2.29.4

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- package.json
bumping main to 3.0 branch
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/290
> bumping main to 3.0

- .github/workflows/remote-integ-tests-workflow.yml
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
Correct AD branch reference for 2.x to avoid the breaking change on main branch
Getting integration tests running and passing
> Correct AD branch reference for 2.x

- package.json
- yarn.lock
Bump `terser` and `loader-utils` dependencies to resolve CVEs.
Pulled in new tarballs by running `yarn osd bootstrap`
> Bump terser and loader-utils deps

- .github/workflows/remote-integ-tests-workflow.yml
Add branch constants in CI workflow, so when running in non-main branches, we can easily persist & change the version of the source repositories (AD plugin & FTRepo plugin)
> Add branch constants in CI workflow

- package.json
- yarn.lock
Fix CVE by version-bumping decode-uri-component. Coming from core Dashboards so we simply update the resolved tarball.
> Bump decode-uri-component

- public/pages/utils/anomalyResultUtils.ts
It is possible that entity.name is undefined when we artificially add whitespace strings as the entity values when the heatmap is empty (see [getSampleAnomaliesHeatmapData()](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/public/pages/AnomalyCharts/utils/anomalyChartUtils.tsx#L240-L248)). If true, set the entire string as 'None'
Confirmed populated entities still show as expected, and 'None' shows for empty charts.
Screenshots:
Closes #152  …
> Fix undefined entity list when heatmap is empty

- package.json
- yarn.lock
> Bump json5 to 2.2.3

- public/pages/DetectorResults/containers/AnomalyResults.tsx
New message:
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/377
> Update cold start message

- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/helpers.ts
Previously, we didn't actually add filter type when loading old detector. This PR fixed that.
Testing done:
1. added a unit tes
2. verified e2et
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/403
> upgrade filter bug

- public/pages/DetectorResults/containers/AnomalyResults.tsx
Required minimum intervals to finish cold start is related to shingle size. This PR adds the shingle size in the computation and puts the result in the cold start message.
Testing done:
1. verified changing shingle size will change the message.
> Changed required minimum intervals in cold start message

- public/pages/Overview/utils/constants.tsx
Instead of setting an explicit value for how many sample index replicas should be created based on cluster configuration (number of nodes, number of awareness attributes/AZs, etc.), we can simplify this by consuming cluster defaults. Note that we were overriding the defaults with the default value anyways (`0-1`) so by default, there will be no change if users don't override the defaults to begin with
I've confirmed changes don't change functionality, sample indices and detectors still work as expected and are able to be created.
Closes #417  …
> Remove `auto_expand_replicas` override in sample data indices

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.6.0.0.md
> Add 2.6 release notes

- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/unit-tests-workflow.yml
The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.
> Fix Node.js and Yarn installation in CI

- public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
- public/pages/AnomalyCharts/containers/AnomalyDetailsChart.tsx
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorResults/containers/AnomalyResults.tsx
run prettier command against all files
N/A
> run prettier command against all files

- opensearch_dashboards.json
- public/expressions/constants.ts
- public/expressions/overlay_anomalies.ts
- public/plugin.ts
- public/services.ts
Creates and registers an expression function to retrieve anomalies from AD as a vis-layer to be rendered on top of visualizations in OSD.
The expression function takes a detectorId argument and utilizes the date range in the context to fetch anomalies. The anomalies are then returned as vis-layer which visualize_embeddable in OSD renders onto the given visualization.
This PR is rebased directly from the featureAnywhere project. It doesn't have the changes to public/plugins.tsx as that code is yet unmerged. The only lines added there are: 
```
plugins.expressions.registerFunction(overlayAnomaliesFunction);
setClient(core.http);
```
For more information on following Developer …
> Adding expression function to retrieve anomalies 

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/styles.scss
This pr includes:
- Fix the formik values props is not getting updated issue
- tweak the code to reuse existing DataFilterList to render the data filter portion on the flyout
- tweak the code to reuse existing FeatureAccordion to render the Find anomalies based on dropdown portion on the flyout
- fix the add feature button style
Issues waiting to be resolved:
- populate fields dropdown list in DataFilterList component and feature component
- fix EnhancedAccordion and MiniAccordion default opening issue
- add formik field value validation schema
- grab dynamic values from all formik fields to submit to create detector
For more information …
> Update data filter setting by using existing DataFilterList componenet

- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/Container/Container.js
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AssociateExisting/containers/AssociateExisting.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AssociateExisting/index.ts
- public/models/interfaces.ts
Adds the ability to associate with an existing detector. Only shows detectors that aren't already associated to that visualization and are single entity.
> [ForDemoPurpose] Associate with existing detector functionality

- .github/CODEOWNERS
- MAINTAINERS.md
updating the list of maintainers and code owners for ad-dashboards
resolves #421 
> Updating maintainers and code owners

- public/pages/DefineDetector/components/NameAndDescription/__tests__/NameAndDescription.test.tsx
In order to ensure that we are able to support node 18, we want to have passing unit tests. Node 15+ doesn't support uncaught promises or errors within tests. I changed it to only return a string instead and gave a description so it only fails for the name check for the given test.
#485 
> fixing test to pass with node 18

- test/jest.config.js
- test/mocks/transformMock.js
- test/mocks/transformMock.ts
tested with newly added unit test
```
$ ../../node_modules/.bin/jest --config ./test/jest.config.js --updateSnapshot AddAnomalyDetector.test.tsx
PASS  public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.test.tsx (90.94 s)
AddAnomalyDetector
✓ renders (7 ms)
› 1 snapshot written.
Snapshot Summary
› 1 snapshot written from 1 test suite.
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 written, 1 total
Time:        92.327 s
Ran all test suites matching /AddAnomalyDetector.test.tsx/i.
```
Was seeing jest test failed on getting osd dark mode svg import. This pr adds jest transform mock to fix this
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> add jest transform config

- .github/CODEOWNERS
- MAINTAINERS.md
- public/pages/DefineDetector/components/NameAndDescription/__tests__/NameAndDescription.test.tsx
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.7.0.0.md
merging main to featureAnywhere branch 
> Merging main branch into featureAnywhere

- public/action/ad_dashboard_action.tsx
- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/__tests__/AssociatedDetectors.test.tsx
- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/utils/helpers.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AssociateExisting/containers/AssociateExisting.tsx
- public/expressions/__tests__/overlay_anomalies.test.ts
- public/expressions/helpers.ts
- public/services.ts
Added unit tests for associated detectors and several bug fixes:
1. changed error statement when detectors fails to create
2. changed detector be undefined and not {} when not selected in AssociateExisting workflow which previously led to empty fields.
3. fixed so correct eligible visualizations are used 
4. Added pluginEventType so anomalies render on tool tip in OSD
> Various bug fixes and unit tests for AssociatedDetectors

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/helpers.tsx
- public/utils/constants.ts
- public/utils/contextMenu/getActions.tsx
- Previously the detector name and feature name formatting regex was not in effective because the formatted value was not store or assign the variable, need to assign the return value of the replace function to the variable. Now we are replacing not allowed characters from vis to `_` when prefilling detector name and feature name
- updated feature anywhere documentation link to https://opensearch.org/docs/latest/observing-your-data/ad/dashboards-anomaly-detection/
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …
> make feature anywhere formatted detector name an assgiend value

- public/pages/Dashboard/utils/utils.tsx
https://tiny.amazon.com isn't available outside of Amazon.com's internal network, there shouldn't be any links to that service.  When looking where the link resolved to, it didn't seem to provide any insight into the current codebase, so I'm removing.
- Related https://github.com/opensearch-project/security-dashboards-plugin/pull/1420
> Remove invalid link

- public/action/ad_dashboard_action.tsx
- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AssociateExisting/containers/AssociateExisting.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/helpers.tsx
- public/plugin.ts
1. Fixed so vislayers aren't mandatory for assocation to be created.
2. Various UI fixes such as keeping link text from wrapping, not letting association detector button expand, changing link to open in new tab and aligning some of the text in flyout. 
> Additional visual fixes for anywhere flyout

- public/utils/contextMenu/getActions.tsx
Adds a category and order to the context menu group for the dashboard integration. This allows the context menu to be grouped with Anomalies and View Event.
https://github.com/opensearch-project/ux/issues/66
> add group category and order for context menu

- public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
- public/pages/AnomalyCharts/index.scss
Remove styling that overrides OUI styles globally and replaces it with props that replicate the removed styling. There is no visual change, apart from parts of Dashboards outside of anomaly detection that were caught in this styling.
Closes #509
> Remove global OUI style override

- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
Add a space between categorical text and the learn more link
> update categorical field text on Feature Anywhere flyout

- public/action/ad_dashboard_action.tsx
- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/plugin.ts
Passing in UISettings to the vis eligibility check and also making sure we can't create detectors when in editing mode.
> Fixing visualization eligibility 

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/plugin.ts
- public/services.ts
- public/utils/constants.ts
- public/utils/contextMenu/getActions.tsx
render embeddable differently based on this change - https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4250
update anomaly detection icon based on this change - https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4408/files
> render embeddable by using vis embeddable

- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/EnhancedAccordion/EnhancedAccordion.tsx
- public/expressions/helpers.ts
- public/pages/DetectorConfig/containers/Features.tsx
2 updates:
1. Updates the event time in the anomaly results to be start time
2. Adds `data-test-subj` fields to several components when used in integration tests
> [Feature Anywhere] Change to anomaly start time; add test ids

- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/plugin.ts
- public/services.ts
Adding a call out on the associated detectors and add anomaly detector flyouts when the limit of associations has been reached for that monitor.
> Adding a callout on flyout when association limit has been reached

- public/pages/AnomalyCharts/containers/AnomaliesChart.tsx
- public/pages/AnomalyCharts/index.scss
- public/pages/Dashboard/utils/utils.tsx
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.8.0.0.md
merging main into featureAnywhere branch
> Merge main into featureAnywhere

- package.json
- yarn.lock
This PR addresses a CVE related to our use of a version of moment.js that is below 2.29.2.
Modified as per the reference PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1931/files
Testing done:
1. Executed an end-to-end test to ensure that we can still create and run a detector with the updated moment.js version.
> Resolve Moment.js CVE Issue

- .github/workflows/remote-integ-tests-workflow.yml
Remove version dependency in cypress workflow by fetching the OpenSearch version value from config file. Now, the auto-created version bump PRs should be sufficient to update all places where versions need bumped.
Moved around steps a bit so the version could be fetched before spinning up OpenSearch cluster
> Remove version dependency in cypress workflow

- .github/workflows/remote-integ-tests-workflow.yml
Manual backport of #554 
Includes fix of version not being assigned correctly due to how github actions env vars work across different steps. This is fixed in `main` via #556 
> [Backport 2.x] Remove version dependency in cypress workflow (#554)

- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
Updates saved object loader `findAll()` calls to include a `hasReference` argument so only objects that include the desired vis ID as a reference will be fetched. Part of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4595.
Other line changes are formatting done by `prettier`.
Tested against cluster with the change in OSD, works as expected.
> Optimize fetching of `augment-vis` saved objects 

- package.json
- yarn.lock
Bumped semver versions to address dependabot alerts.
> Bumped semver to latest legacy version

- package.json
- yarn.lock
Bumped semver versions to address dependabot alerts.
> [Backport 1.3] Bumped semver to latest legacy version

- .github/workflows/remote-integ-tests-workflow.yml
This PR has 2 improvements:
1. Update glob to include subdirectories.  Test specs have been added under `vis_augmenter` subdirectory as part of [this PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/752) and are currently not running in this workflow.
2. Remove env vars to just fetch the same branch that the workflow is running from. For example, in `main`, this will fetch `main` branches of all the repos. This follows what is done in OSD repo. It also helps prevent conflicts and lessens the differences between `main`/`2.x`. …
> Cypress workflow improvements

- .github/workflows/remote-integ-tests-workflow.yml
Backport 53677c54a8df8e2e77a5cb34f98acd5e7c202ab9 to `2.x`
> [Backport 2.x] Cypress workflow improvements (#560)

- public/pages/DetectorsList/containers/ConfirmActionModals/utils/helpers.tsx
When starting or stopping detectors, the pop-up window shows the detector names as `DETECTOR_NAME />` where "DETECTOR\_NAME" is the name of the detector.
The markup seems to have residual `/>` that are rendered to the user. Remove them to ensure they do not appear between the opening and the closing EuiLink tags.
To reproduce:
1. Visit https://playground.opensearch.org/app/anomaly-detection-dashboards#/detectors?from=0&size=20&search=&indices=&sortField=name&sortDirection=asc
2. Check a few detectors
3. Click on Actions > Stop real-time detectors
> Fix display of detector names

- public/pages/DetectorResults/containers/AnomalyHistory.tsx
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.11.0.0.md
This PR improves the intermediate loading state on the historical results page. Before, an initial load of the page would send requests to the server-side with an empty task ID, which would return a 404 not found due to the path not existing, and show empty results. This is because there would be a double slash `//` where the task ID was supposed to be in between- e.g., `/api/anomaly_detectors/detectors//results/` (_note this would only happen if the page was directed via direct URL or refresh, or from the 'View results' button on the detector list page. If navigating from the detector results tab to the historical tab, the issue was not seen since the detector details were already populated in redux store_). Typically, this was quickly re-executed with a populated task ID after it was …
> Prevent empty task IDs passed to server side

- .github/CODEOWNERS
- MAINTAINERS.md
Adding @dbwiddis / @owaiskazi19 / @joshpalis to maintainers and codeowners files for this repository.
> Update maintainers & codeowners

- babel.config.js
Resolved
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/658
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/647
Should backport to 2.x
> fix build error due to missing babel plugins

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.12.0.0.md
> Add 2.12 release notes

- package.json
- yarn.lock
Updates versions of `@adobe/css-tools` and `browserify-sign` to non-CVE-impacted versions.
- ~[ ] New functionality includes testing.~
- ~[ ] All tests pass~
- ~[ ] New functionality has been documented.~
> [1.3] Upgrade css-tools and browserify-sign versions

- .eslintrc.yml
- package.json
- yarn.lock
Remove a legacy dependency not needed by plugins anymore. The consequence is it removes a huge amount of transitive dependencies in `yarn.lock`, many of which are dated and frequently cause CVE-related issues.
Testing done
- `yarn build` works
- `yarn osd bootstrap` works
- sanity test on a local domain
~~Still understanding other potential impacts and original reasoning for having this dependency, will update here when more is learned from @opensearch-project/opensearch-core team.~~ UPDATE: this has been confirmed by @kavilla , no other concerns. …
> Remove legacy dependency

- .eslintrc.yml
- package.json
- yarn.lock
Manual backport of #702 . Cloned the latest 2.x environments and re-ran bootstrap to fetch the relevant dependencies for 2.x.
Testing done:
`yarn test:jest`: all unit tests successful
`yarn osd bootstrap`: successful
`yarn build`: successful
`yarn start` / local cluster: ran basic workflows, no issues found
> [Backport 2.x] Remove legacy dependency

- public/pages/DetectorsList/containers/List/List.tsx
Previously, the selected indices in the URL query params was not getting assigned to the page state on initial load. This fixes that.
> Populate selected indices from query params on initial load

- public/models/interfaces.ts
- public/pages/Dashboard/Container/DashboardOverview.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DetectorsList/containers/List/List.tsx
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
- public/pages/utils/helpers.ts
- public/redux/reducers/ad.ts
- public/redux/reducers/alerting.ts
- public/redux/reducers/anomalyResults.ts
- public/redux/reducers/opensearch.ts
- public/redux/reducers/previewAnomalies.ts
- public/redux/reducers/sampleData.ts
Previously, we define dataSourceId as empty if it doesn't exist url. However, mds team introduced a change that treats empty dataSourceId as the local cluster scenario, and only undefined actionOption will render the default remote data source. Therefore, we have to adopt this change and assign dataSourceId as undefined when it's not presented in the url.
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/721
> update actionOption attribution for all data soure components

- .github/workflows/build-and-test-workflow.yml
- .github/workflows/remote-integ-tests-workflow.yml
- .github/workflows/verify-binary-installation.yml
I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.
Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
https://github.com/opensearch-project/dashboards-observability/pull/309
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5952
For more information on following …
> Add workflow to verify binary installation works

- package.json
- public/pages/Dashboard/Container/DashboardOverview.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DetectorsList/containers/List/List.tsx
- public/pages/DetectorsList/utils/__tests__/helpers.test.ts
- public/pages/DetectorsList/utils/helpers.ts
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
- public/pages/main/Main.tsx
- public/pages/utils/helpers.ts
- server/utils/constants.ts
- yarn.lock
This PR includes the following bug fixes:
- side navigation bar link doesn't work when data source is local cluster
- when local cluster is selected, it always jump back to default data source selection on fresh 
- the first breadcrumb doesn't work on list page when local cluster is selected
The above two bugs are fixed by making the following changes:
- update breadcrumbs setting on list page. The previous implementation inverted MDS enabled case and MDS disabled case
- make sure when checking if dataSourceId is set in the url, only set dataSourceId as undefined when the query param dataSourceId is undefined
- introduce a new prop - landingDataSourceId that keeps track of if dataSourceId exist in the url on landing pages (Overview page and Dashboard page). In this way, default data …
> MDS local cluster scanrio bug fixes

- public/pages/DefineDetector/components/Datasource/DataSource.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
This pr includes three things:
- update Data Source card title to Select Data on create page to avoid confusion with MDS support
- clean selections on create page when switching data sources
- only append dataSourceId to the create page url when MDS is enabled
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/assets/41348518/e9c3e6f4-bcb3-47d4-a772-113c913a7ede
> clean selected field values when switching data source on create page

- .github/workflows/build-and-test-workflow.yml
- .github/workflows/remote-integ-tests-workflow.yml
- package.json
- public/pages/DetectorResults/containers/AnomalyResults.tsx
- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- public/pages/utils/anomalyResultUtils.ts
- release-notes/opendistro-for-elasticsearch.anomaly-detection-kibana-plugin.release-notes-1.7.0.0.md
This PR addresses a data non-population issue observed in HC detectors. When setting the time horizon in the anomaly overview to the past hour, two boxes appeared in the heatmap. However, clicking on both resulted in no data being populated. Extending the time horizon to three hours increased the number of boxes to six, but similarly, clicking on these boxes also resulted in no data appearing.
The root cause of the issue is a mismatch in time references: the time displayed in the HC heatmap cells is calculated based on the anomaly plot time, which corresponds to data_end_time. However, when querying data within the HC heatmap cell's time range, data_start_time was used instead.
This PR updates sorting and querying fields from `DATA_START_TIME` to `DATA_END_TIME` to align with the data …
> build query parameters using data_end_time

- .github/workflows/verify-binary-installation.yml
Fixes the version of OpenSearch for the binary download
> Use correct 2.x version for Dashboards binary

- .github/workflows/remote-integ-tests-workflow.yml
The introduction of `sleep` between test runs in `dashboard_spec.js` and `detector_list_spec.js` was initially implemented to handle timing issues. However, these tests were actually failing due to a recent URL change, as detailed in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1257.
With the root cause of the failures addressed, the delays introduced by `sleep` commands are now redundant and can potentially slow down the testing process without providing any benefit. This PR removes these unnecessary sleep intervals between test executions.
**Testing Done:**
- Confirmed that all remote Cypress tests pass without the sleep intervals.
For …
> Remove unnecessary sleep between test runs

- public/pages/AnomalyCharts/utils/__tests__/anomalyChartUtils.test.ts
- public/pages/AnomalyCharts/utils/anomalyChartUtils.tsx
- public/pages/utils/__tests__/anomalyResultUtils.test.ts
- public/pages/utils/anomalyResultUtils.ts
This PR addresses a bug that occurred when categorical values contained special characters such as colons. Previously, entities were stored as a comma-separated name-value pair string in the heatmap cell's custom data field. When a cell was clicked, the custom data was retrieved and the string was split via colons. This caused errors if the categorical value itself contained colons or if multiple name-value pairs included commas.
To fix this issue, this PR changes the storage format to a JSON string in the cell's custom data. When a cell is clicked, the JSON object is restored. Since JSON naturally handles special characters, this eliminates the need for additional special character handling.
Additionally, the previous implementation stored a newline-separated name-value pair in the …
> Fix handling of special characters in categorical values

- package.json
- public/pages/DetectorDetail/containers/DetectorDetail.tsx
- public/pages/DetectorDetail/containers/__tests__/CustomIndexErrorMsg.test.tsx
- public/redux/reducers/__tests__/utils.ts
- test/jest.config.js
- test/setupTests.ts
Customers were receiving a warning message about the detectors we have created on a production cluster. The message incorrectly warned that the result index for the detector is custom and is not present on the cluster, and would be recreated when real-time or historical detection starts for the detector. However, real-time detection had already been started for these detectors, and the result index did exist. Customers could consistently reproduce the bug, although I only succeeded once when creating a detector immediately after a cluster started.
The issue may arise from a potential race condition in the code when the statement finishes before the cat indices call completes (see this code segment https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/public/pa …
> Fix Warning Message About Custom Result Index Despite Existing Indices

- public/models/interfaces.ts
- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/models/interfaces.ts
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/constants.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
- public/pages/ReviewAndCreate/components/DetectorDefinitionFields/DetectorDefinitionFields.tsx
- public/pages/ReviewAndCreate/components/__tests__/DetectorDefinitionFields.test.tsx
- public/pages/ReviewAndCreate/components/__tests__/__snapshots__/DetectorDefinitionFields.test.tsx.snap
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/pages/ReviewAndCreate/utils/helpers.ts
- public/redux/reducers/__tests__/utils.ts
update create detector page and detector detail page to add custom result index lifecycle management settings
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/assets/41348518/eae9a505-f272-4608-8c80-271b9292f984
https://github.com/opensearch-project/anomaly-detection/issues/1213
> update create detector page and detector detail page to add custom result index lifecycle management settings

- package.json
- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
- public/pages/DetectorDetail/containers/DetectorDetail.tsx
- public/pages/DetectorDetail/containers/__tests__/CustomIndexErrorMsg.test.tsx
- public/pages/DetectorDetail/utils/helpers.tsx
- public/pages/ReviewAndCreate/components/DetectorDefinitionFields/DetectorDefinitionFields.tsx
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/redux/reducers/__tests__/anomalyResults.test.ts
- public/redux/reducers/__tests__/liveAnomalyResults.test.ts
- public/redux/reducers/anomalyResults.ts
- public/redux/reducers/liveAnomalyResults.ts
This PR finalizes the frontend changes related to [PR #1225](https://github.com/opensearch-project/anomaly-detection/pull/1225). The custom result index query now uses an index pattern instead of a single index.
Additionally, this PR addresses an issue where missing custom result indices would appear because the original code checked for the existence of an index name, but now we use it as a prefix. We have updated the logic to perform a prefix search instead of checking for index name equality.
This PR also resolves issue #765 by downgrading the version of jest-canvas-mock.
Testing Done:
* Added unit tests.
* Verified that the custom result index missing callout is not shown.
* Confirmed that the frontend can still display old and new results after a rollover. …
> Update Frontend for Custom Result Index Query and Fix Issues

- public/expressions/helpers.ts
- public/expressions/overlay_anomalies.ts
When reopening the create detector feature anywhere flyout after creating the detector, there's an error complaining about search anomalies API . The reason for that is dataSourceId was forgotten to be passed into the getAnomalies call
> fix a MDS related bug on feature anywhere page

- public/components/FeatureAnywhereContextMenu/AssociatedDetectors/containers/AssociatedDetectors.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AddAnomalyDetector.tsx
- public/components/FeatureAnywhereContextMenu/CreateAnomalyDetector/AssociateExisting/containers/AssociateExisting.tsx
fix a bug in mds feature anywhere associated detectors part - associated detectors are not showing in associated detectors flyout
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/assets/41348518/224c272c-f0b0-4419-a9f7-21935a0f4adf
> mds feature anywhere associated detectors fix

- .github/workflows/remote-integ-tests-workflow.yml
This PR updates the frontend CI configuration to set up JDK 21, aligning with the baseline JDK 21 already set on the backend (https://github.com/opensearch-project/anomaly-detection/pull/1228). Without this update, remote tests in CI would fail with the error: "error: release version 21 not supported."
Testing:
* Verified that remote tests in CI pass successfully with JDK 21.
> Update Frontend CI to Use JDK 21

- public/pages/DefineDetector/components/Timestamp/Timestamp.tsx
- public/pages/DefineDetector/components/Timestamp/__tests__/Timestamp.test.tsx
- public/pages/DefineDetector/components/Timestamp/__tests__/__snapshots__/Timestamp.test.tsx.snap
- public/redux/reducers/opensearch.ts
This change is enabling the selection of **date_nanos** date type for creating detectors in the plugin. The feature has been merged on the plugin side 
https://github.com/opensearch-project/anomaly-detection/pull/1238 and is being backported to 2.X : 
https://github.com/opensearch-project/anomaly-detection/pull/1249
The change add the **date_nanos** dataType and enable its selection as a date field. 
I could test the change by cherry-picking this commit this code to 2.14 branch and testing OpenSearch Dashboard against a cluster with the patched anomaly-detection plugin (to pass validation on date_nanos). 
The mapping of the timestamp field is the following 
```
"timestamp" : {
"type" : "date_nanos",
"format" : "epoch_millis||yyyy-MM-dd HH:mm:ss.SSS||yyyy-MM-dd HH:mm:ss.SSSSSS||yyyy-MM-dd …
```
> feat: allow date_nanos dates in timestamp selection

- package.json
- yarn.lock
address CVE-2024-4068 and update yarn.lock file
> address CVE-2024-4068

- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
fix an issue that causes dataSourceId to not show in the URL on Overview landing page
> fix an issue that causes dataSourceId to not show in the URL on Overview landing page

- public/models/interfaces.ts
- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/DefineDetector/models/interfaces.ts
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/constants.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
- public/pages/ReviewAndCreate/components/DetectorDefinitionFields/DetectorDefinitionFields.tsx
- public/pages/ReviewAndCreate/components/__tests__/DetectorDefinitionFields.test.tsx
- public/pages/ReviewAndCreate/components/__tests__/__snapshots__/DetectorDefinitionFields.test.tsx.snap
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/pages/ReviewAndCreate/utils/helpers.ts
- public/redux/reducers/__tests__/utils.ts
Add Enable Flattened custom result index checkbox to allow customer to enable this feature
https://github.com/user-attachments/assets/a9d768ea-a0fc-41e0-8c4b-5e6e805d8835
https://github.com/opensearch-project/anomaly-detection/issues/1213
> Add Enable Flattened custom result index checkbox

- test/setup.jest.ts
Upstream core dashboard added new dependency @osd/monaco in autocomplete provider. Anomaly dashboards previously had tests where indirectly triggers autocomplete registration in [data plugin](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/plugin.ts#L171-L172), and the load of autocomplete providers [SQL](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/antlr/opensearch_sql/code_completion.ts#L6) and [DQL](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/antlr/dql/code_completion.ts#L9)
```
Cannot find module '!!raw-loader!../../target/public/xjson.editor.worker.js' from '../../packages/osd-monaco/target/xjson/language.js'
Require stack: …
```
> [Test] Fix monaco import issue in UTs

- public/pages/ConfigureModel/containers/ConfigureModel.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DetectorDetail/containers/DetectorDetail.tsx
- public/pages/DetectorJobs/containers/DetectorJobs.tsx
- public/pages/ReviewAndCreate/containers/ReviewAndCreate.tsx
DataSourceView is broken on future playground and TrineoApp, however, no console/network errors shown and can't reproduce it locally. 
Pull 2.16 and 2.15 docker image and tested with them. Found that it only breaks under 2.16 docker. The only change between 2.15 and 2.16 is adding this dataSourceFilter for version decoupling work. Suspecting it is because the dataSourceFilter filtered out the version so DataSourceView is giving error says "cannot find data source". Since the scenario where AD uses DataSourceView doesn't require data source filtering, I'm removing the dataSourceFilter check for all DataSourceView usage in AD. 
As it cannot be reproduced locally, confirmed the fix with deploying the docker image. 
By submitting this pull request, I …
> Remove dataSourceFilter that breaks DataSourceView

- .github/workflows/remote-integ-tests-workflow.yml
- public/models/interfaces.ts
- public/models/types.ts
- public/pages/ConfigureModel/components/AdvancedSettings/AdvancedSettings.tsx
- public/pages/ConfigureModel/components/AdvancedSettings/__tests__/AdvancedSettings.test.tsx
- public/pages/ConfigureModel/containers/ConfigureModel.tsx
- public/pages/ConfigureModel/models/interfaces.ts
- public/pages/ConfigureModel/utils/__tests__/helpers.test.tsx
- public/pages/ConfigureModel/utils/helpers.ts
- public/pages/DefineDetector/utils/constants.tsx
- public/pages/DetectorConfig/components/AdditionalSettings/AdditionalSettings.tsx
- public/pages/DetectorConfig/containers/Features.tsx
- public/pages/DetectorConfig/containers/__tests__/DetectorConfig.test.tsx
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
- public/pages/ReviewAndCreate/components/AdditionalSettings/AdditionalSettings.tsx
- public/pages/ReviewAndCreate/components/AdditionalSettings/SuppressionRulesModal.tsx
- public/pages/ReviewAndCreate/components/ModelConfigurationFields/ModelConfigurationFields.tsx
- public/pages/ReviewAndCreate/components/__tests__/AdditionalSettings.test.tsx
- public/pages/ReviewAndCreate/components/__tests__/ModelConfigurationFields.test.tsx
- public/pages/ReviewAndCreate/components/__tests__/__snapshots__/AdditionalSettings.test.tsx.snap
- public/pages/ReviewAndCreate/components/__tests__/__snapshots__/ModelConfigurationFields.test.tsx.snap
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/pages/ReviewAndCreate/utils/helpers.ts
- public/redux/reducers/__tests__/utils.ts
- public/utils/utils.tsx
This PR introduces suppression anomaly rules under the Advanced Settings section, enabling users to suppress anomalies based on the difference between expected and actual values, either as an absolute value or a relative percentage.
Testing:
* Added unit tests to verify the suppression rules functionality.
* Conducted manual end-to-end (e2e) tests to validate the implementation.
Note most of changes are snapshot file changes:
```
git diff 3ed0058a9c8b52dc8a34b11f4869f0dda6904e2a --stat -- '*.snap'
.../containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap | 1563 +++++++++++++++++++++++++++++-
.../__tests__/__snapshots__/AdditionalSettings.test.tsx.snap        |  824 ++++++++++------
.../__tests__/__snapshots__/ModelConfigurationFields.test.tsx.snap  |  413 +++++--- …
```
> Add ignore rules comparing actual and expected values

- public/models/interfaces.ts
- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/DefineDetector/models/interfaces.ts
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/constants.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
- public/pages/ReviewAndCreate/components/DetectorDefinitionFields/DetectorDefinitionFields.tsx
- public/pages/ReviewAndCreate/components/__tests__/DetectorDefinitionFields.test.tsx
- public/pages/ReviewAndCreate/components/__tests__/__snapshots__/DetectorDefinitionFields.test.tsx.snap
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/pages/ReviewAndCreate/utils/helpers.ts
- public/redux/reducers/__tests__/utils.ts
This reverts commit f53450c733ca32341cec5f5295086b64ce6a04ae.
> Revert "Add Enable Flattened custom result index checkbox (#830) (#833)"

- package.json
- yarn.lock
address cve - https://github.com/advisories/GHSA-952p-6rrq-rcjv
> address CVE-2024-4067

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.17.0.0.md
> add 2.17 release notes

- .github/workflows/remote-integ-tests-workflow.yml
- opensearch_dashboards.json
- public/components/DiscoverAction/SuggestAnomalyDetector.test.tsx
- public/components/DiscoverAction/SuggestAnomalyDetector.tsx
- public/plugin.ts
- public/services.ts
- public/utils/constants.ts
This PR implements a small enhancement for the suggest anomaly detector feature, we add feedback button to the flyout of suggest anomaly detector, when users click the button, it will call the metric report API in the core plugin usageCollection. And when LLM gives suggested parameters successfully, a `generated` metric is reported, when the suggested detector is created, a `created` metric is reported.
Another change is that we check the feature flag before register the SuggestAnomalyDetector action to Discover, if the feature flag is disabled or the whole assistant capability is disabled, no action will be registered.
Some UI change:
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/816
By submitting this pull request, I confirm that my contribution is …
> Report metrics for suggest anomaly detector

- public/plugin.ts
Based on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8332, anomaly detection needs to make some adjustment to flatten the menus in analytics(all) use case.
> [navigation]feat: update category to flatten menus in analytics(all) use case

- .github/workflows/remote-integ-tests-workflow.yml
- public/pages/ConfigureModel/containers/ConfigureModel.tsx
- public/pages/ConfigureModel/containers/SampleAnomalies.tsx
- public/pages/ConfigureModel/containers/__tests__/SampleAnomalies.test.tsx
- public/pages/ConfigureModel/utils/__tests__/helpers.test.tsx
- public/pages/ConfigureModel/utils/helpers.ts
This commit resolves a bug where the preview did not account for suppression rules and imputation options. The fix involves passing additional parameters to handle these configurations correctly.
This PR also fixes cypress CI issue "Timeout for 600 seconds reached. OpenSearch Dashboards did not finish compiling." by following https://github.com/opensearch-project/dashboards-observability/pull/2187 and https://github.com/opensearch-project/dashboards-observability/pull/2196
Testing:
* e2e testing completed.
* UT added to cover the new logic. …
> Fix preview not considering rules and imputation options

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-2.18.0.0.md
> Add 2.18 release notes

- public/components/DiscoverAction/SuggestAnomalyDetector.test.tsx
- public/components/DiscoverAction/SuggestAnomalyDetector.tsx
- public/utils/contextMenu/getActions.tsx
This PR adds some small enhancements and fixes some bugs for the suggestAD feature, which contains:
1. Do not show the suggestAD action button if the data source of the selected index pattern has no AI agent.
2. If the selected index pattern doesn't have time field, then we use the root level date type field as the default timestamp field.
3. If cannot find any date type field from the mappings of the selected index pattern, then pops up an error.
4. Feature name cannot be longer than 64, so we truncate the feature name if it exceeds the limit.
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/816
https://github.com/user-attachments/assets/5c9ff2aa-ea20-4d1b-a521-33a37dab6b58
By submitting this pull request, I confirm that my contribution is made under the …
> Do not show suggestAD action if the data source has no AI agent

- public/pages/Dashboard/Container/DashboardOverview.tsx
- public/pages/DetectorsList/containers/List/List.tsx
- public/pages/Overview/containers/AnomalyDetectionOverview.tsx
- public/redux/reducers/ad.ts
- public/redux/reducers/previewAnomalies.ts
This pr includes two mds bug fixes:
- surround dispatch calls with `if (!dataSourceEnabled || (MDSOverviewState.selectedDataSourceId && MDSOverviewState.selectedDataSourceId !== ""))` check to make sure when mds is enabled, we wait until the selected data source and selected data source id is ready before doing any dispatch calls. This saves us from seeing a transient error message says cannot get all detectors even though the page is actually functioning.
- fix a bug in the way how we get dataSourceId in preview anomalies api, getting it from request body instead of as a parameter. 
For more information on following Developer …
> mds bug fixes

- package.json
- yarn.lock
Backport b06f1f71c7e6ecb2d7e48d2bd8b987481dff2c1b from #864 (Fixes CVE-2024-4067)
Backport 2496e1b598bb4a46c372a842b71f5a430027d806 from #709 (Fixes CVE-2023-26159 and CVE-2024-28849)
Ran `yarn install` (Fixes CVE-2023-45857)
> [1.3] Multiple backports to fix CVEs

- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
disable the flatten result index option when:
- is on edit page
- is using custom result index
- flatten result index is not checked for existing detector config
customer can chose to create a detector with flatten result index option, and then later on edit page, they can uncheck it to disable flatten result index.  
> disable flatten result index option for existing detectors

- public/models/interfaces.ts
- public/pages/DefineDetector/components/CustomResultIndex/CustomResultIndex.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/DefineDetector/models/interfaces.ts
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/constants.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/DetectorConfig.test.tsx.snap
- public/pages/DetectorConfig/containers/__tests__/__snapshots__/Features.test.tsx.snap
- public/pages/ReviewAndCreate/components/DetectorDefinitionFields/DetectorDefinitionFields.tsx
- public/pages/ReviewAndCreate/components/__tests__/DetectorDefinitionFields.test.tsx
- public/pages/ReviewAndCreate/components/__tests__/__snapshots__/DetectorDefinitionFields.test.tsx.snap
- public/pages/ReviewAndCreate/containers/__tests__/__snapshots__/ReviewAndCreate.test.tsx.snap
- public/pages/ReviewAndCreate/utils/helpers.ts
- public/redux/reducers/__tests__/utils.ts
> backport flatten result index related change into 2.x

- .github/workflows/changelog_verifier.yml
- CHANGELOG.md
- DEVELOPER_GUIDE.md
Add changelog verifier workflow for creating release notes faster
> Add changelog verifier workflow

- package.json
- yarn.lock
Upgrade axios to 1.8.2 to fix SSRF & credential leakage vulnerability
https://advisories.opensearch.org/advisory/GHSA-jr5f-v2jv-69x6 
> fix(security): Upgrade axios to 1.8.2 to fix SSRF 

- server/routes/opensearch.ts
changing from using transport client for field caps call to the opensearch-js client directly.
resolves #969 
> Switching fieldcaps api to utilize js client

- babel.config.js
- package.json
- yarn.lock
Requires `@babel/runtime` version 7.26.10 or higher
Resolves [CVE-2025-27789](https://nvd.nist.gov/vuln/detail/CVE-2025-27789)
- ~[ ] New functionality includes testing.~
- ~[ ] All tests pass~
- ~[ ] New functionality has been documented.~
> Update @babel/runtime to >=7.26.10

- .github/workflows/verify-binary-installation.yml
- CHANGELOG.md
- opensearch_dashboards.json
- package.json
Increment version to 3.0.0.0-beta1
related #568 
> Increment version to 3.0.0.0-beta1

- public/pages/DefineDetector/components/Datasource/DataSource.tsx
- public/pages/ReviewAndCreate/components/DataConnectionFlyout/DataConnectionFlyout.tsx
This PR fixes 2 different bugs related to remote cluster display during detector creation:
1. When local cluster and remote cluster have the same name we distinguish which cluster is the local/remote one
2. When we click on previous in the model configuration page it will display the correct cluster selection and not reset to just show local cluster
Both these cases are covered in new IT in this PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1755
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#devel …
> Fix remote cluster bug when remote and local have same name

- CHANGELOG.md
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-3.0.0.0-beta1.md
Adding release notes for 3.0.0.0-beta1
#568 
> Adding release notes for 3.0.0.0-beta1

- public/pages/DefineDetector/components/Datasource/DataSource.tsx
- public/pages/DefineDetector/containers/DefineDetector.tsx
- public/pages/DefineDetector/containers/__tests__/DefineDetector.test.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
- public/pages/DefineDetector/utils/__tests__/helpers.test.tsx
- public/pages/DefineDetector/utils/helpers.ts
- public/redux/reducers/__tests__/utils.ts
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-3.0.0.0-beta1.md
Added clusters definition when converting from detector object to formik props so the clusters will show up correctly when editing a detector
> Display selected clusters correctly on edit page

- release-notes/opensearch-anomaly-detection-dashboards.release-notes-3.0.0.0.md
- adding release notes for 3.0.0.0
- Release Notes for 3.0.0 should include all changes from alpha1+beta1+GA in 1 file
> adding release notes for 3.0.0.0

- public/pages/ConfigureForecastModel/components/AdvancedSettings/AdvancedSettings.tsx
- public/pages/ConfigureForecastModel/components/AdvancedSettings/__tests__/AdvancedSettings.test.tsx
- public/pages/DefineForecaster/containers/DefineForecaster.tsx
- public/pages/ForecastDetail/components/ForecastChart/ForecastChart.tsx
- public/pages/ForecastersList/containers/ConfirmActionModals/ForecasterActionsCell.tsx
- release-notes/opensearch-anomaly-detection-dashboards.release-notes-3.1.0.0.md
- Add spacing between the Create Forecaster form and footer for easier interaction.
- Remove unsupported Sparse Data Handling option from forecasting UI.
- Clean up unnecessary console.log statements.
Testing done:
- manual test
> Improve Create Forecaster UI and cleanup logs

- public/utils/contextMenu/getActions.tsx
@lezzago mentioned that the suggest feature only works with opensearch index pattern or indices. This PR prevents it to show up if the selected dataset is not opensearch index
> Restrict `Suggest anomaly detector` to only show for OpenSearch datasets

- public/pages/DefineDetector/components/DataFilterList/DataFilterList.tsx
- public/pages/DefineDetector/components/DataFilterList/components/DataFilter.tsx
- public/pages/DefineDetector/containers/__tests__/__snapshots__/DefineDetector.test.tsx.snap
When creating anomaly detectors with multiple data filters or long Query DSL filters, the Next button would disappear from the bottom of the page, preventing users from proceeding with detector creation. I added two fixes, one too truncate long filters with ... and also to wrap if we have lots of filters in a row
Screenshots:
resolves #715 
> Wrap data filter in detector creation

- package.json
- yarn.lock
> Bump elliptic to 6.6.1

- .github/workflows/verify-binary-installation.yml
- opensearch_dashboards.json
- package.json
- public/pages/ConfigureForecastModel/components/SuggestParametersDialog/SuggestParametersDialog.tsx
- public/pages/ForecastersList/containers/ConfirmActionModals/ForecasterActionsCell.tsx
- public/pages/ForecastersList/containers/List/List.tsx
- server/routes/forecast.ts
- test/setup.jest.ts
This PR
- Enforce a minimum shingle size (`min={4}`) in `SuggestParametersDialog` to prevent invalid configurations.
- Fetch the complete forecaster list by explicitly passing `size: MAX_FORECASTER` in `forecast.searchForecaster`; replace wildcard imports with `MAX_FORECASTER`.
- Remove unnecessary `console.log` statements and commented-out code from `ForecasterActionsCell` and `ForecastersList` for cleaner output.
- Fix the delete-action bug where deleting the selected forecaster incorrectly deleted the last forecaster in the list. Now correctly uses the selected forecaster's object for retrieving the name and ID.
Testing:
- Manual verification completed.
For more …
> fix: fetch full forecaster list, and fix delete bug

- public/pages/DefineForecaster/containers/DefineForecaster.tsx
- public/pages/ForecastersList/components/ListFilters/ListFilters.tsx
- public/pages/ForecastersList/containers/List/List.tsx
- public/pages/utils/__tests__/helpers.test.ts
- public/pages/utils/helpers.ts
In environments running OpenSearch versions lower than 3.1, the forecasting backend is not enabled. Without this guard, users would still see the incompatible data source in forecasting pages, click into it, and encounter backend errors. Previously, the compatibility check relied on supportedOSDataSourceVersions in opensearch_dashboards.json, but this was only applied at the plugin level. Since forecasting and Anomaly Detection share the same plugin, the existing minimum compatible version in data source (>=2.9.0) did not prevent <3.1 data sources from appearing on forecasting pages. This PR ensures that forecasting has its own data source compatibility check.
Also, while the isDataSourceCompatible helper was intended to filter unsupported data sources, it failed for …
> Hide data sources below 3.1 in forecasting pages
